using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Linq;

namespace Demo_03.Class
{
    class Car
    {
        #region Attribute
        int id=default;// 4 byte in heap 
        string? model=default; // 4 byte in heap to reference
        double speed=default;// 4 byte in heap 

        #endregion

        #region Properties 
        //encapsulation 
        //هنا المفروض استخدم automatic property علشان انا مش محتاج اعمل validation بس عادي 
        public int Id
        {
            get { return id; }
            set { id = value; }
        }

        public string? Model
        {
            get { return model; }
            set { model = value; }
        }

        public double Speed
        {
            get { return speed; }
            set { speed = value; }
        }

        #endregion

        #region Constructor 
        //Empty parameterless Constructor [Defualt Constructor] لعند لما يكون في Constructor
        //Auto-Generated by Compiler 
        //public Car()
        //{
        //    //Empty
        //}
        public Car(int id, string? model, double speed)
        {
            this.id = id;
            this.model = model;
            this.speed = speed;
            Console.WriteLine("CTor 01");
        }
        //هنا انت لو مش عملت pass ل attribute هيطلع error  علشان بقى فيه user define constructor 

        //this
        //this = الـ reference للكائن الحالي.
        //بتشاور على نفس الكائن اللي انت عملته بـ new.
        //بتستخدمها غالبًا علشان تفرّق بين الـ attributes والـ parameters لو ليهم نفس الاسم.
        //-------------------------------------------------------------------------------------------------
        //overload Constructor and Chaining Constructor
        //follow presentation
        public Car(int id,string model):this(id,model,180)
        {
            //this.id = id;
            //this.model = model;
            //speed = 180;
            Console.WriteLine("CTor 02");
        }
        public Car(int id):this(id,"SBC")
        {
            //this.id = id;
            //this.model = "SBC";
            //speed = 120;
            Console.WriteLine("CTor 03");
        }

        #endregion

        #region Method 
        public override string ToString()
        {
            return $"Id = {Id} \n Mode = {Model} \n Speed = {speed}";
        }
        #endregion
    }
}
